version: "3.4"
services:
  node01:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      - NAME=node01
      - PEER=10.151.0.20
    sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.default.rp_filter=0
        - net.ipv4.conf.all.rp_filter=0
    privileged: true
    networks:
        netA:
            ipv4_address: 10.151.0.10
  node02:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      - NAME=node02
      - PEER=10.151.0.10
    sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.default.rp_filter=0
        - net.ipv4.conf.all.rp_filter=0
    privileged: true
    networks:
        netA:
            ipv4_address: 10.151.0.20
networks:
    netA:
        driver_opts:
            com.docker.network.driver.mtu: 1500
        ipam:
            config:
                - subnet: 10.151.0.0/24